### ISSUE TITLE
Workflow run

### ISSUE THREAD

**Issue by BruAPAHE** [Paperspace/gradient-cli#405]
Hi, i trying  run workflow but got error
gradient   version: v2.0.6
```
gradient workflows run  --id {id} --path .gradient/workflows/workflow.yaml
Failed to fetch data: Github url is invalid.
```

workflow.yaml
```
'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  HelloWorld:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: python /inputs/repo/hello.py
      image: tensorflow/tensorflow:1.14.0-py3
      ```
